#!/bin/tcsh -f


foreach x (*.tex)
echo $x
#sed -e 's/\[ppp/\[{\\it ppp\\\/}/g'   $x >$x.neu
#sed -e 's/_S/_{\\mbox{\\footnotesize S}}/g'   $x >$x.neu
#sed -e 's/Lesetips/Literatur/g'   $x >$x.neu
#sed -e 's/\\end{figure}/\\end{figure}%/g'   $x >$x.neu
#sed -e 's/(\\ibox{\([0-9]*\)})/\\iboxb{\1}/g'   $x >$x.neu
#sed -e 's/ vform-/ \{\\sc vform}-/g'   $x >$x.neu
#sed -e 's/"=/-/g'   $x >$x.neu
#sed -e 's/\\isc{\([[:graph:]]*\)}\\is{\([[:graph:]]*\)}/\\isce{\1}{\2}/g'   $x >$x.neu
#sed -e 's/s\\textsc{cop}e}/scope/g'   $x >$x.neu
#perl -CIOED -p -e 's/\\il{(\p{Script_Extensions=Han}+)\s+(\p{ASCII}+)}/\\ilce{$1}{$2}/g' $x >$x.neu
#perl -CIOED -p -e 's/\\isc{(\p{Script_Extensions=Han}+)}\\is{(\p{ASCII}+)}/\\isce{$1}{$2}/g' $x >$x.neu
#perl -CIOED -p -e
#'s/\\isc{(\p{Script_Extensions=Han}+)!(\p{Script_Extensions=Han}+)-}\\is{(\p{ASCII}+)!(\p{ASCII}+)-}/\\iscesub{$1}{$3}{$2-}{$4-}/g'
#$x >$x.neu
#perl -CIOED -p -e 's/\\isc{(\p{Script_Extensions=Han}+)\|\(}\\is{(\p{ASCII}+)\|\(}/\\isce[|(]{$1}{$2}/g' $x >$x.neu
#perl -CIOED -p -e #'s/\\isc{(\p{Script_Extensions=Han}+)\|\)}\\is{(\p{ASCII}+)\|\)}/\\isce[|)]{$1}{$2}/g' $x >$x.neu
#perl -CIOED -p -e
#'s/\\isce{(\p{Script_Extensions=Han}+)!(\p{Script_Extensions=Han}+)!(\p{ASCII}+)}{(\p{ASCII}+)!(\p{ASCII}+)!(\p{ASCII}+)}/\\iscesubsub{$1}{$4}{$2}{$5}{$3}{$6}/g'
#$x >$x.neu
#sed -e 's/indexcxgc/indexcxg/g'   $x >$x.neu
#sed -e 's/indexgpsgc/indexgpsg/g'   $x >$x.neu
#sed -e 's/indexhpsgstopc/indexhpsgstop/g'   $x >$x.neu
#sed -e 's/\\textsc{art}.\\textsc{def}/\\defart{}/g'   $x >$x.neu
#sed -e 's/\\defart{}\./\\defart\./g'   $x >$x.neu
#sed -e 's/\\defart{}]/\\textsc{da}]/g'   $x >$x.neu
#sed -e 's/; \\defart{}]/; \\textsc{da}]/g'   $x >$x.neu
#sed -e 's/;\\defart{}/;\\textsc{da}/g'   $x >$x.neu
#sed -e 's/：\\footnote/：\\dotfootnote/g'   $x >$x.neu
#sed -e 's/：\\dotfootnote/：\\colonfootnote/g'   $x >$x.neu
#sed -e 's/。\\footnote/。\\dotfootnote/g'   $x >$x.neu
#sed -e 's/\\aimention/\\ia/g'   $x >$x.neu
sed -e 's/{Gazdar81}/{Gazdar81a}/g'   $x >$x.neu
end


#foreach x (*.tex)
#echo $x
#sed -e 's/subind}{Scrambling/subind}{Scrambling@\{\\it Scrambling\\\/\}/g' $x >$x.neu
#end

foreach x (*.tex)
printf "."
mv -f $x $x.old
mv $x.neu $x
end

printf "\n"

